{{- if .Values.prometheus.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  type: ClusterIP
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  ports:
    - port: {{ .Values.containerPorts.port }}
      protocol: TCP
      targetPort: {{ .Values.prometheus.serviceMonitor.targetPort }}
{{- end }}
