{{- if .Values.prometheus.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "certManager.webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: webhook
spec:
  type: ClusterIP
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
  ports:
    - name: https
      port: 443
      targetPort: {{ .Values.webhook.containerPorts.port }}
{{- end }}
